name: Run tests

on:
  - push

jobs:
  uv-example:
    name: python
    runs-on: jrottenberg/ffmpeg:ffmpeg-7.1-ubuntu2404

    steps:
      - uses: actions/checkout@v4

      - name: Setup UV with caching
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Test with pytest
        run: |
          uv run pytest tests --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
