name: Run tests

on:
  - push

jobs:
  uv-example:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup UV with caching
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install dependencies and test with pytest
        run: |
          # Installing missing packages on image
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          # Pulling dev dependencies for test
          uv sync --dev
          # Running tests
          uv run pytest tests --cov=src --cov-branch --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
